source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASByr_Example', :exclusive => true do
  pod 'ASByr', :path => '../'
end

target 'ASByr_Tests', :exclusive => true do
  pod 'ASByr', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
